/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package probando;

import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.GraphicsConfiguration;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;

/**
 *
 * @author Jonas
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    private SimpleUniverse universo=null;
    Clase3d lampara = new Clase3d();
    Clase3d silla = new Clase3d();
    Clase3d camara = new Clase3d();
    HiloMover hiloMueve ;
    public static double lim =0;
     
    public Ventana() {
        initComponents();
        //GraphicsConfiguration config=SimpleUniverse.getPreferredConfiguration();
        GraphicsConfiguration con = SimpleUniverse.getPreferredConfiguration();  // objeto para configurar graficos
        Canvas3D lienzo=new Canvas3D(con);  // crear el lienzo en 3d
        ///x,y,alto,ancho 
        lienzo.setBounds(0, 0, 800, 700);   // darle el tamano
        this.setSize(800, 700);
        this.setResizable(false);
        this.add(lienzo);                  // agregar el lienzo a la ventana
        this.pack();                       // enpaquetar
        BranchGroup scene= lampara.crearEscenaY_Lampara();// llamar la escena grafica
        BranchGroup scene2= silla.crearSilla();
        BranchGroup scene3= camara.crearCamara();
        // agregar el lienzo y la escena grafica al objeto universo
        universo = new  SimpleUniverse(lienzo);
        universo.getViewingPlatform().setNominalViewingTransform();
        universo.addBranchGraph(scene);
        universo.addBranchGraph(scene2);
        universo.addBranchGraph(scene3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuellos = new javax.swing.JButton();
        esfera = new javax.swing.JButton();
        botonSilla = new javax.swing.JButton();
        botonSilla2 = new javax.swing.JButton();
        lamparaD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        camaraIzq = new javax.swing.JButton();
        camaraDer = new javax.swing.JButton();
        camAba = new javax.swing.JButton();
        camArri = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cuellos.setBackground(new java.awt.Color(255, 255, 255));
        cuellos.setForeground(new java.awt.Color(51, 51, 255));
        cuellos.setText("Girar Lampara Izquierda");
        cuellos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuellosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuellosMouseReleased(evt);
            }
        });

        esfera.setBackground(new java.awt.Color(255, 255, 255));
        esfera.setForeground(new java.awt.Color(51, 51, 255));
        esfera.setText("Rotar Lampara");
        esfera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                esferaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                esferaMouseReleased(evt);
            }
        });

        botonSilla.setBackground(new java.awt.Color(0, 0, 0));
        botonSilla.setForeground(new java.awt.Color(255, 255, 255));
        botonSilla.setText("Girar Silla Izquierda");
        botonSilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSillaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonSillaMouseReleased(evt);
            }
        });

        botonSilla2.setBackground(new java.awt.Color(0, 0, 0));
        botonSilla2.setForeground(new java.awt.Color(255, 255, 255));
        botonSilla2.setText("Girar Silla Derecha");
        botonSilla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSilla2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonSilla2MouseReleased(evt);
            }
        });

        lamparaD.setBackground(new java.awt.Color(255, 255, 255));
        lamparaD.setForeground(new java.awt.Color(51, 51, 255));
        lamparaD.setText("Girar Lampara Derecha");
        lamparaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lamparaDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lamparaDMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lampara");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Silla");

        camaraIzq.setBackground(new java.awt.Color(255, 255, 255));
        camaraIzq.setText("Camara Izquierda");
        camaraIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                camaraIzqMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                camaraIzqMouseReleased(evt);
            }
        });

        camaraDer.setBackground(new java.awt.Color(255, 255, 255));
        camaraDer.setText("Camara Derecha");
        camaraDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                camaraDerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                camaraDerMouseReleased(evt);
            }
        });

        camAba.setBackground(new java.awt.Color(255, 255, 255));
        camAba.setText("Camara Abajo");
        camAba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                camAbaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                camAbaMouseReleased(evt);
            }
        });

        camArri.setBackground(new java.awt.Color(255, 255, 255));
        camArri.setText("Camara Arriba");
        camArri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                camArriMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                camArriMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Camara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(813, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(camaraDer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cuellos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(esfera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonSilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonSilla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lamparaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(camaraIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(camAba, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camArri, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(camArri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camAba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camaraDer)
                .addGap(18, 18, 18)
                .addComponent(camaraIzq)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(botonSilla2)
                .addGap(18, 18, 18)
                .addComponent(botonSilla)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lamparaD)
                .addGap(18, 18, 18)
                .addComponent(cuellos)
                .addGap(18, 18, 18)
                .addComponent(esfera)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esferaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esferaMousePressed
      hiloMueve = new HiloMover(lampara.movimientoObjeto[3],lampara.objeto3D[3],1); /// cuando se deja presionado el boton se activa el hilo
      hiloMueve.start();
    }//GEN-LAST:event_esferaMousePressed

    private void esferaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esferaMouseReleased
     hiloMueve.stop(); //cuando se suelta el boton el hilo se detiene
    }//GEN-LAST:event_esferaMouseReleased

    private void cuellosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuellosMousePressed
     hiloMueve = new HiloMover(lampara.movimientoObjeto[2],lampara.objeto3D[2],2);
     hiloMueve.start();
    }//GEN-LAST:event_cuellosMousePressed

    private void cuellosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuellosMouseReleased
     hiloMueve.stop();
    }//GEN-LAST:event_cuellosMouseReleased

    private void botonSillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSillaMousePressed
     hiloMueve = new HiloMover(silla.movimientoObjeto[9],silla.objeto3D[9],2);
     hiloMueve.start();
    }//GEN-LAST:event_botonSillaMousePressed

    private void botonSillaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSillaMouseReleased
     hiloMueve.stop(); 
    }//GEN-LAST:event_botonSillaMouseReleased

    private void botonSilla2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSilla2MousePressed
     hiloMueve = new HiloMover(silla.movimientoObjeto[9],silla.objeto3D[9],3);
     hiloMueve.start(); 
    }//GEN-LAST:event_botonSilla2MousePressed

    private void botonSilla2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSilla2MouseReleased
     hiloMueve.stop(); 
    }//GEN-LAST:event_botonSilla2MouseReleased

    private void lamparaDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamparaDMousePressed
     hiloMueve = new HiloMover(lampara.movimientoObjeto[2],lampara.objeto3D[2],3);
     hiloMueve.start();  
    }//GEN-LAST:event_lamparaDMousePressed

    private void lamparaDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamparaDMouseReleased
     hiloMueve.stop(); 
    }//GEN-LAST:event_lamparaDMouseReleased

    private void camaraIzqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camaraIzqMousePressed
     hiloMueve = new HiloMover(camara.movimientoObjeto[3],camara.objeto3D[3],4);
     hiloMueve.start(); 
    }//GEN-LAST:event_camaraIzqMousePressed

    private void camaraIzqMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camaraIzqMouseReleased
     hiloMueve.stop();  
    }//GEN-LAST:event_camaraIzqMouseReleased

    private void camaraDerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camaraDerMousePressed
     hiloMueve = new HiloMover(camara.movimientoObjeto[3],camara.objeto3D[3],5);
     hiloMueve.start(); 
    }//GEN-LAST:event_camaraDerMousePressed

    private void camaraDerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camaraDerMouseReleased
     hiloMueve.stop(); 
    }//GEN-LAST:event_camaraDerMouseReleased

    private void camAbaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camAbaMousePressed
     hiloMueve = new HiloMover(camara.movimientoObjeto[3],camara.objeto3D[3],6);
     hiloMueve.start(); 
    }//GEN-LAST:event_camAbaMousePressed

    private void camAbaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camAbaMouseReleased
      hiloMueve.stop();  
    }//GEN-LAST:event_camAbaMouseReleased

    private void camArriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camArriMousePressed
     hiloMueve = new HiloMover(camara.movimientoObjeto[3],camara.objeto3D[3],7);
     hiloMueve.start();   
    }//GEN-LAST:event_camArriMousePressed

    private void camArriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camArriMouseReleased
     hiloMueve.stop();  
    }//GEN-LAST:event_camArriMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSilla;
    private javax.swing.JButton botonSilla2;
    private javax.swing.JButton camAba;
    private javax.swing.JButton camArri;
    private javax.swing.JButton camaraDer;
    private javax.swing.JButton camaraIzq;
    private javax.swing.JButton cuellos;
    private javax.swing.JButton esfera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lamparaD;
    // End of variables declaration//GEN-END:variables
}
